# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SampInfo_Win.ui'
#
# Created: Sat Dec 08 20:40:06 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SampInfoForm(object):
    def setupUi(self, SampInfoForm):
        SampInfoForm.setObjectName("SampInfoForm")
        SampInfoForm.resize(457, 840)
        self.gridLayout = QtGui.QGridLayout(SampInfoForm)
        self.gridLayout.setObjectName("gridLayout")
        self.samp_info_frame = QtGui.QFrame(SampInfoForm)
        self.samp_info_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.samp_info_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.samp_info_frame.setObjectName("samp_info_frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.samp_info_frame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sampinfo_widget = QtGui.QSplitter(self.samp_info_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampinfo_widget.sizePolicy().hasHeightForWidth())
        self.sampinfo_widget.setSizePolicy(sizePolicy)
        self.sampinfo_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.sampinfo_widget.setOrientation(QtCore.Qt.Vertical)
        self.sampinfo_widget.setOpaqueResize(True)
        self.sampinfo_widget.setObjectName("sampinfo_widget")
        self.sampinfo_frame = QtGui.QFrame(self.sampinfo_widget)
        self.sampinfo_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.sampinfo_frame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.sampinfo_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sampinfo_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.sampinfo_frame.setObjectName("sampinfo_frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.sampinfo_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 2, 1, 1)
        self.samp_info_image_label = QtGui.QLabel(self.sampinfo_frame)
        self.samp_info_image_label.setMinimumSize(QtCore.QSize(0, 0))
        self.samp_info_image_label.setMaximumSize(QtCore.QSize(300, 300))
        self.samp_info_image_label.setStyleSheet("background-color: rgb(108, 140, 255);")
        self.samp_info_image_label.setText("")
        self.samp_info_image_label.setTextFormat(QtCore.Qt.AutoText)
        self.samp_info_image_label.setScaledContents(True)
        self.samp_info_image_label.setWordWrap(True)
        self.samp_info_image_label.setObjectName("samp_info_image_label")
        self.gridLayout_2.addWidget(self.samp_info_image_label, 2, 1, 1, 1)
        self.AsseatImage_label = QtGui.QLabel(self.sampinfo_frame)
        self.AsseatImage_label.setMinimumSize(QtCore.QSize(0, 0))
        self.AsseatImage_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.AsseatImage_label.setObjectName("AsseatImage_label")
        self.gridLayout_2.addWidget(self.AsseatImage_label, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.sampinfo_widget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.name_label = QtGui.QLabel(self.frame_2)
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_3.addWidget(self.name_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.type_label = QtGui.QLabel(self.frame_2)
        self.type_label.setText("")
        self.type_label.setObjectName("type_label")
        self.horizontalLayout_5.addWidget(self.type_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.file_label = QtGui.QLabel(self.frame_2)
        self.file_label.setText("")
        self.file_label.setObjectName("file_label")
        self.horizontalLayout_4.addWidget(self.file_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.file_Size_label = QtGui.QLabel(self.frame_2)
        self.file_Size_label.setText("")
        self.file_Size_label.setObjectName("file_Size_label")
        self.horizontalLayout_6.addWidget(self.file_Size_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.date_label = QtGui.QLabel(self.frame_2)
        self.date_label.setText("")
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_7.addWidget(self.date_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.Version_comboBox = QtGui.QComboBox(self.frame_2)
        self.Version_comboBox.setObjectName("Version_comboBox")
        self.horizontalLayout_8.addWidget(self.Version_comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.asseat_path = QtGui.QLabel(self.frame_2)
        self.asseat_path.setMaximumSize(QtCore.QSize(300, 16777215))
        self.asseat_path.setText("")
        self.asseat_path.setObjectName("asseat_path")
        self.verticalLayout_8.addWidget(self.asseat_path)
        self.import_Asseat_btn = QtGui.QPushButton(self.frame_2)
        self.import_Asseat_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.import_Asseat_btn.setObjectName("import_Asseat_btn")
        self.verticalLayout_8.addWidget(self.import_Asseat_btn)
        spacerItem4 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.sampinfo_widget)
        self.gridLayout.addWidget(self.samp_info_frame, 0, 0, 1, 1)

        self.retranslateUi(SampInfoForm)
        QtCore.QMetaObject.connectSlotsByName(SampInfoForm)

    def retranslateUi(self, SampInfoForm):
        SampInfoForm.setWindowTitle(QtGui.QApplication.translate("SampInfoForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.AsseatImage_label.setText(QtGui.QApplication.translate("SampInfoForm", "AsseatImage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SampInfoForm", "详细信息", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SampInfoForm", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SampInfoForm", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SampInfoForm", "FileType:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SampInfoForm", "FileSize:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SampInfoForm", "setDate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("SampInfoForm", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.import_Asseat_btn.setText(QtGui.QApplication.translate("SampInfoForm", "Import", None, QtGui.QApplication.UnicodeUTF8))

